[package]
name = "website"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.48"
markdown = "1.0.0"
maud = "0.27.0"
serde = "1.0.226"
serde_derive = "1.0.226"
toml = "0.9.7"
walkdir = "2.5.0"
